In [12]:
import pandas as pd
import numpy as np

In [63]:
import numpy as np

def cargar_datoa(ruta_archivo):
  datos = np.genfromtxt('/content/retail_sales_dataset.csv', delimiter=',', skip_header=1)
  return datos

  datos = cargar_datoa('/content/retail_sales_dataset.csv')
  print(datos)

In [59]:
# Verificar que no hay valores nulos en las columnas numéricas
print(df.isnull().sum())

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [13]:
df = pd.read_csv('/content/retail_sales_dataset.csv')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [15]:
df.describe()

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

In [16]:
df.shape

(1000, 9)

In [18]:
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [19]:
df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [20]:
print(df['Product Category'].unique())

['Beauty' 'Clothing' 'Electronics']

Calcula el total de ventas por categoría de producto.

In [31]:
beauty = df[df['Product Category'] == 'Beauty']
clothing = df[df['Product Category'] == 'Clothing']
electronics = df[df['Product Category'] == 'Electronics']
total_beauty = np.sum(beauty['Total Amount'])
total_clothing = np.sum(clothing['Total Amount'])
total_electronics= np.sum(electronics['Total Amount'])
print(f"Total ventas Beauty: {total_beauty}")
print(f"Total ventas Clothing: {total_clothing}")
print(f"Total ventas Electronics: {total_electronics}")

Total ventas Beauty: 143515
Total ventas Clothing: 155580
Total ventas Electronics: 156905

Calcula el promedio de ventas diarias por categoría de producto.

In [34]:
np.mean(beauty['Total Amount'])
np.mean(clothing['Total Amount'])
np.mean(electronics['Total Amount'])
print(f"Promedio ventas Beauty: {np.mean(beauty['Total Amount']):.2f}")
print(f"Promedio ventas clothing: {np.mean(clothing['Total Amount']):.2f}")
print(f"Promedio ventas electronics: {np.mean(electronics['Total Amount']):.2f}")

Promedio ventas Beauty: 467.48
Promedio ventas clothing: 443.25
Promedio ventas electronics: 458.79

Identifica las categorías de productos con mayores y menores ventas.

In [41]:
totales = np.array([total_beauty, total_clothing, total_electronics])
categorias = np.array(['Beauty', 'Clothing', 'Electronics'])

idx_max = np.argmax(totales)
idx_min = np.argmin(totales)

print(f"Categoría con mas ventas: {categorias[idx_max]} con {totales[idx_max]} ventas")
print(f"Categoría con menos ventas: {categorias[idx_min]} con {totales[idx_min]} ventas")

Categoría con mas ventas: Electronics con 156905 ventas
Categoría con menos ventas: Beauty con 143515 ventas

porcentaje del total de ventas por categoria

In [58]:
total_general = np.sum([total_beauty, total_clothing, total_electronics])
print(f"Total ventas general: {total_general}")
porcentaje_beauty = total_beauty / total_general *100
print(f"Beauty: {porcentaje_beauty:.2f}%")
porcentaje_clothing = total_clothing / total_general *100
print(f"clothing: {porcentaje_clothing:.2f}%")
porcentaje_electronics = total_electronics / total_general *100
print(f"electronics: {porcentaje_electronics:.2f}%")

Total ventas general: 456000
Beauty: 31.47%
clothing: 34.12%
electronics: 34.41%